apiVersion: v1
kind: Service
metadata:
  name: queries
  labels:
    app: rode
  namespace: rode
spec:
  selector:
    app: queries
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queries
  labels:
    app: rode
  namespace: rode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queries
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: queries
    spec:
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      - name: tmp
        persistentVolumeClaim:
          claimName: tmp
      containers:
      - name: queries
        image: seslhd/rode.queries:3.0.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
            cpu: 0
          limits:
            memory: 4Gi
            cpu: 2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: logs
          mountPath: /logs
        - name: tmp
          mountPath: /tmp
        envFrom:
        - configMapRef:
            name: entities
        - configMapRef:
            name: config
        # livenessProbe:
        #   httpGet:
        #     path: /{{- if ne .name "ui" }}{{ .name }}{{- end }}
        #     port: {{ .port | default 80 }}
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        #   failureThreshold: 2{{- end }}
      imagePullSecrets:
      - name: regcred