apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: rode
  namespace: rode
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: rode
  namespace: rode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ui
    spec:
      volumes:
      - name: logs
        persistentVolumeClaim: 
          claimName: logs
      containers:
      - name: ui
        image: seslhd/rode.ui:3.0.2
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
            cpu: 0
          limits:
            memory: 4Gi
            cpu: 2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: logs
          mountPath: /logs
        env:
        # Language ENV values
        - name: STAGE
          value: production
        # Configmaps
        - name: REACT_APP_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: config
              key: DOMAIN
        # Secrets
        - name: REACT_APP_GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: TOKEN.GOOGLE
        # livenessProbe:
        #   httpGet:
        #     path: /{{- if ne .name "ui" }}{{ .name }}{{- end }}
        #     port: {{ .port | default 80 }}
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        #   failureThreshold: 2{{- end }}
      imagePullSecrets:
      - name: regcred